baseURL = "https://github.io/diafcon/Diafcon.github.io"
languageCode = "en-us"
title = "Official Diafon Docs"
paginate = 6
preserveTaxonomyNames = true
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[permalinks]
  posts = "/:year/:month/:slug/"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "日本語"
    weight = 2
  [languages.pl]
    languageName = "Polski"
    weight = 3

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]
